### ISSUE TITLE
レビュー依頼内容

### ISSUE THREAD

**Issue by sakiko0921** [sakiko0921/2024_portfolio#34]
■Webアプリの概要
PFCバランスの基づいたまとめがいのお買い物リストを作成するアプリです。
※PFC → タンパク質、脂質、炭水化物の英語の頭文字をとったもの

■ProjectsのURL
[作成したProjectsのURL](https://github.com/users/sakiko0921/projects/4/views/1)

■MVPリリースまで
- [ ] rails new
- [ ] Render.comにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] お買い物リスト作成機能
- [ ] 栄養素量による食材候補リコメンド機能
- [ ] 新規食材登録機能
- [ ] googleログイン機能

■MVP後
- [ ] パスワードリセット機能
- [ ] リストのLINEでの共有機能

■MVPレビュー依頼予定日
予定日：2024年 9月 1日

**Comment by sakiko0921** [comment]
レビューよろしくお願いいたします。

**Comment by beppumasaki** [comment]
概ね良いかと思います。LGTMです。
